# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusPowerEndurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', models.IntegerField()),
                ('time', models.IntegerField()),
                ('rung', models.IntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')])),
                ('feet_on', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FingerEndurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FingerMuscularEndurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FingerPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LateralCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_left_side', models.IntegerField()),
                ('distance_right_side', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaxPullUps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.IntegerField()),
                ('lateral', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MaxWeightPullUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('lateral', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MetricDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MetricTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_tests', to='training.Session')),
            ],
        ),
        migrations.CreateModel(
            name='PullAndSlap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_right_hand', models.IntegerField()),
                ('height_left_hand', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_and_slaps', to='metrics.MetricTest')),
            ],
        ),
        migrations.AddField(
            model_name='maxweightpullup',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_weight_pull_ups', to='metrics.MetricTest'),
        ),
        migrations.AddField(
            model_name='maxpullups',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_pull_ups', to='metrics.MetricTest'),
        ),
        migrations.AddField(
            model_name='lateralcore',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lateral_core', to='metrics.MetricTest'),
        ),
        migrations.AddField(
            model_name='fingerpower',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finger_power_tests', to='metrics.MetricTest'),
        ),
        migrations.AddField(
            model_name='fingermuscularendurance',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finger_muscular_endurance_tests', to='metrics.MetricTest'),
        ),
        migrations.AddField(
            model_name='fingerendurance',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finger_endurance_tests', to='metrics.MetricTest'),
        ),
        migrations.AddField(
            model_name='campuspowerendurance',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_power_endurance', to='metrics.MetricTest'),
        ),
    ]
