# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-03 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusPowerEndurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', models.IntegerField()),
                ('time', models.IntegerField()),
                ('rung', models.IntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')])),
                ('feet_on', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FingerEndurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('rung', models.IntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')])),
                ('feet_on', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FingerMuscularEndurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FingerPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LateralCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_left_side', models.IntegerField()),
                ('distance_right_side', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaxPullUps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.IntegerField()),
                ('lateral', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MaxWeightPullUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('lateral', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MetricDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MetricTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_tests', to='training.Session')),
            ],
        ),
        migrations.CreateModel(
            name='PullAndSlap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_right_hand', models.IntegerField()),
                ('height_left_hand', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_and_slaps', to='metrics.MetricTest')),
            ],
        ),
        migrations.CreateModel(
            name='SendingLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boulder_onsight', models.IntegerField(blank=True, choices=[(0, 'V0'), (1, 'V1'), (2, 'V2'), (3, 'V3'), (4, 'V4'), (5, 'V5'), (6, 'V6'), (7, 'V7'), (8, 'V8'), (9, 'V9'), (10, 'V10'), (11, 'V11')], null=True)),
                ('boulder_redpoint', models.IntegerField(blank=True, choices=[(0, 'V0'), (1, 'V1'), (2, 'V2'), (3, 'V3'), (4, 'V4'), (5, 'V5'), (6, 'V6'), (7, 'V7'), (8, 'V8'), (9, 'V9'), (10, 'V10'), (11, 'V11')], null=True)),
                ('route_onsight', models.IntegerField(blank=True, choices=[(0, '5.8'), (1, '5.9'), (2, '5.10a'), (3, '5.10b'), (4, '5.10c'), (5, '5.10d'), (6, '5.11a'), (7, '5.11b'), (8, '5.11c'), (9, '5.11d'), (10, '5.12a'), (11, '5.12b'), (12, '5.12c'), (13, '5.12d'), (14, '5.13a'), (15, '5.13b'), (16, '5.13c'), (17, '5.13d'), (18, '5.14a')], null=True)),
                ('route_redpoint', models.IntegerField(blank=True, choices=[(0, '5.8'), (1, '5.9'), (2, '5.10a'), (3, '5.10b'), (4, '5.10c'), (5, '5.10d'), (6, '5.11a'), (7, '5.11b'), (8, '5.11c'), (9, '5.11d'), (10, '5.12a'), (11, '5.12b'), (12, '5.12c'), (13, '5.12d'), (14, '5.13a'), (15, '5.13b'), (16, '5.13c'), (17, '5.13d'), (18, '5.14a')], null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_level', to='metrics.MetricTest')),
            ],
        ),
        migrations.AddField(
            model_name='maxweightpullup',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_weight_pull_ups', to='metrics.MetricTest'),
        ),
        migrations.AddField(
            model_name='maxpullups',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_pull_ups', to='metrics.MetricTest'),
        ),
        migrations.AddField(
            model_name='lateralcore',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lateral_core', to='metrics.MetricTest'),
        ),
        migrations.AddField(
            model_name='fingerpower',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finger_power_tests', to='metrics.MetricTest'),
        ),
        migrations.AddField(
            model_name='fingermuscularendurance',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finger_muscular_endurance_tests', to='metrics.MetricTest'),
        ),
        migrations.AddField(
            model_name='fingerendurance',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finger_endurance_tests', to='metrics.MetricTest'),
        ),
        migrations.AddField(
            model_name='campuspowerendurance',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_power_endurance', to='metrics.MetricTest'),
        ),
    ]
