# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-14 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0020_auto_20180214_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerEndurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wieght', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FingerMuscularEndurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wieght', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FingerPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wieght', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaxWeightPullUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wieght', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetricTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_tests', to='training.Session')),
            ],
        ),
        migrations.CreateModel(
            name='PullAndSlap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_right_hand', models.IntegerField()),
                ('height_left_hand', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_and_slaps', to='metrics.MetricTest')),
            ],
        ),
        migrations.AddField(
            model_name='maxweightpullup',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_weight_pull_ups', to='metrics.MetricTest'),
        ),
        migrations.AddField(
            model_name='fingerpower',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finger_power_tests', to='metrics.MetricTest'),
        ),
        migrations.AddField(
            model_name='fingermuscularendurance',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finger_muscular_endurance_tests', to='metrics.MetricTest'),
        ),
        migrations.AddField(
            model_name='fingerendurance',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finger_endurance_tests', to='metrics.MetricTest'),
        ),
    ]
