# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-16 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fingerendurance',
            old_name='wieght',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='fingermuscularendurance',
            old_name='wieght',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='fingerpower',
            old_name='wieght',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='maxweightpullup',
            old_name='wieght',
            new_name='weight',
        ),
    ]
