# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-27 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20180215_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusPowerEndurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', models.IntegerField()),
                ('time', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_power_endurance', to='metrics.MetricTest')),
            ],
        ),
        migrations.CreateModel(
            name='LateralCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_left_side', models.IntegerField()),
                ('distance_right_side', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lateral_core', to='metrics.MetricTest')),
            ],
        ),
        migrations.CreateModel(
            name='MaxPullUps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.IntegerField()),
                ('lateral', models.BooleanField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_pull_ups', to='metrics.MetricTest')),
            ],
        ),
        migrations.CreateModel(
            name='MetricDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='maxweightpullup',
            name='lateral',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
