# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-11 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_auto_20180227_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='campuspowerendurance',
            name='feet_on',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campuspowerendurance',
            name='rung',
            field=models.IntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')], default=3),
            preserve_default=False,
        ),
    ]
