# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-27 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_auto_20180327_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boulder_onsight', models.IntegerField(choices=[(0, 'V0'), (1, 'V1'), (2, 'V2'), (3, 'V3'), (4, 'V4'), (5, 'V5'), (6, 'V6'), (7, 'V7'), (8, 'V8'), (9, 'V9'), (10, 'V10'), (11, 'V11')])),
                ('boulder_redpoint', models.IntegerField(choices=[(0, 'V0'), (1, 'V1'), (2, 'V2'), (3, 'V3'), (4, 'V4'), (5, 'V5'), (6, 'V6'), (7, 'V7'), (8, 'V8'), (9, 'V9'), (10, 'V10'), (11, 'V11')])),
                ('route_onsight', models.IntegerField(choices=[(0, '5.8'), (1, '5.9'), (2, '5.10a'), (3, '5.10b'), (4, '5.10c'), (5, '5.10d'), (6, '5.11a'), (7, '5.11b'), (8, '5.11c'), (9, '5.11d'), (10, '5.12a'), (11, '5.12b'), (12, '5.12c'), (13, '5.12d'), (14, '5.13a'), (15, '5.13b'), (16, '5.13c'), (17, '5.13d'), (18, '5.14a')])),
                ('route_redpoint', models.IntegerField(choices=[(0, '5.8'), (1, '5.9'), (2, '5.10a'), (3, '5.10b'), (4, '5.10c'), (5, '5.10d'), (6, '5.11a'), (7, '5.11b'), (8, '5.11c'), (9, '5.11d'), (10, '5.12a'), (11, '5.12b'), (12, '5.12c'), (13, '5.12d'), (14, '5.13a'), (15, '5.13b'), (16, '5.13c'), (17, '5.13d'), (18, '5.14a')])),
            ],
        ),
        migrations.RemoveField(
            model_name='metrictest',
            name='boulder_onsight',
        ),
        migrations.RemoveField(
            model_name='metrictest',
            name='boulder_redpoint',
        ),
        migrations.RemoveField(
            model_name='metrictest',
            name='route_onsight',
        ),
        migrations.RemoveField(
            model_name='metrictest',
            name='route_redpoint',
        ),
        migrations.AddField(
            model_name='sendinglevel',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_level', to='metrics.MetricTest'),
        ),
    ]
