# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditioning',
            name='setNum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
