# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='ape_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='eval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='wingspan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
