# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_conditioning_setnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditioning',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditioning_sets', to='training.RefExercise'),
        ),
    ]
