# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20170921_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditioning',
            name='setNum',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training.Athlete'),
        ),
    ]
