# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20170927_0549'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('athlete', 'sessionDate')]),
        ),
    ]
