# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20170927_1956'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conditioning',
            unique_together=set([('session', 'setNum')]),
        ),
    ]
