# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20170930_2118'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conditioning',
            unique_together=set([('exercise', 'setNum')]),
        ),
    ]
