# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_auto_20171001_0032'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conditioning',
            unique_together=set([]),
        ),
    ]
