# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_auto_20171001_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditioning',
            name='setNum',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
    ]
