# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_auto_20171003_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinchBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('seconds', models.IntegerField()),
                ('pinch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinch_blocks', to='training.RefExercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinch_blocks', to='training.Session')),
            ],
        ),
        migrations.CreateModel(
            name='WeightedHangs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('seconds', models.IntegerField()),
                ('hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighted_hangs', to='training.RefExercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighted_hangs', to='training.Session')),
            ],
        ),
    ]
