# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_pinchblocks_weightedhangs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField()),
                ('event_date', models.DateField()),
                ('event_title', models.CharField(max_length=100)),
                ('event_description', models.CharField(blank=True, max_length=300)),
                ('event_location', models.CharField(blank=True, max_length=200)),
                ('event_format', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='conditioning',
            name='setNum',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], default=1),
        ),
    ]
