# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_auto_20171112_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='Conditioning_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice6', to='training.RefConditioning'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='finger_training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice7', to='training.RefFingerTraining'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='routine_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice4', to='training.RefRoutine'),
        ),
        migrations.AlterField(
            model_name='reftechniquedrill',
            name='secondary_technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technique_drill2', to='training.RefTechnique'),
        ),
    ]
