# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_auto_20171112_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedpractice',
            name='date',
        ),
        migrations.AddField(
            model_name='assignedpractice',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='practice',
            name='date',
            field=models.DateField(auto_now=True),
            preserve_default=False,
        ),
    ]
