# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-25 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_auto_20171122_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxConditioning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_conditioning_sets', to='training.RefExercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_conditioning_sets', to='training.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Top3Sends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(choices=[(1, 'V0'), (2, 'V1'), (3, 'V2'), (4, 'V3')], max_length=4)),
                ('second', models.CharField(choices=[(1, 'V0'), (2, 'V1'), (3, 'V2'), (4, 'V3')], max_length=4)),
                ('third', models.CharField(choices=[(1, 'V0'), (2, 'V1'), (3, 'V2'), (4, 'V3')], max_length=4)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_3_sends', to='training.Session')),
            ],
        ),
        migrations.AlterField(
            model_name='practice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='maxconditioning',
            unique_together=set([('session', 'exercise')]),
        ),
    ]
