# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-25 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_auto_20180214_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLimbingQuotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('quote', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='practice',
            old_name='Conditioning_2',
            new_name='conditioning_2',
        ),
    ]
