# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-27 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_auto_20180324_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='ape_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='wingspan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
